-------------------------------------------------------------------------------
-- File        :  <filename>
-- Author      :  <your name>
-- Company     :  YRGO
-- Created     :  <date>
-- Platform    :  Quartus/Modlesim/Windows
-- Standard    :  VHDL 93
-------------------------------------------------------------------------------
-- Description :  <A few words about this design>
--                
-------------------------------------------------------------------------------
